#!/usr/bin/env python3
""" Defines the BaseModel """
import uuid
from datetime import datetime


class BaseModel():
    """ Defines all attribute/methods for other classes """
    def __init__(self):
        self.id = str(uuid.uuid4())
        self.created_at = datetime.now()
        self.updated_at = datetime.now()

    def __str__(self):
        """ Prints out the classname, id and dict of the class
        [<class name>] (<self.id>) <self.__dict__>
        """
        className = self.__class__.__name__
        instanceId = self.id
        instanceDict = self.__dict__
        return f"[{className}] ({instanceId}) {instanceDict}"

    def save(self):
        """ updates attribute <updated_at> with cuerent DT """
        self.updated_at = datetime.now()

    def to_dict(self):
        """ returns a dictionary containing all
            keys/values of __dict__ """
        my_dict = self.__dict__.copy()
        my_dict["__class__"] = self.__class__.__name__
        my_dict["created_at"] = self.created_at.isoformat()
        my_dict["updated_at"] = self.updated_at.isoformat()
        return my_dict
